repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace  # Xóa khoảng trắng thừa
      - id: end-of-file-fixer    # Đảm bảo file có dòng trống cuối
      - id: check-yaml           # Kiểm tra cú pháp YAML
      - id: debug-statements     # Phát hiện debug print trong code

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black                # Format code Python

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8               # Kiểm tra chuẩn PEP8
